version: '3'
services:
  Lab_inventory-app:
    restart: always
    build: .
    image: kelvindocker123/lab_inventory:jun26
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
    volumes:
      - data-volume:/home/kaining/Lab_inventory/app/base/static

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - Lab_inventory-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  data-volume: